"""adding voting db columns

Revision ID: 3903ca4bf3e4
Revises: 2563e9ab9106
Create Date: 2025-05-28 03:05:47.296646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3903ca4bf3e4'
down_revision = '2563e9ab9106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer()))
        batch_op.add_column(sa.Column('downvotes', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
