"""Games update to fields

Revision ID: 7d99d2ef887b
Revises: c17a53ac86de
Create Date: 2025-07-08 16:06:36.364789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d99d2ef887b'
down_revision = 'c17a53ac86de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_url')
        batch_op.drop_column('wiki_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq2_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq2_users_email'), type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wiki_url', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), nullable=True))
        batch_op.drop_column('developer')

    # ### end Alembic commands ###
