"""adding nullable false constraint to voting columns

Revision ID: ba352d40ce4f
Revises: 3903ca4bf3e4
Create Date: 2025-05-28 03:34:00.453435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba352d40ce4f'
down_revision = '3903ca4bf3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('downvotes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('downvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
