"""Users model update

Revision ID: c17a53ac86de
Revises: ba352d40ce4f
Create Date: 2025-06-26 05:42:42.487231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17a53ac86de'
down_revision = 'ba352d40ce4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), unique=True, nullable=False))
        batch_op.add_column(sa.Column('refresh_token', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
