"""table for games_words users

Revision ID: c47e7c3a052e
Revises: 7d99d2ef887b
Create Date: 2025-07-11 11:58:53.140981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47e7c3a052e'
down_revision = '7d99d2ef887b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_words_link_authors',
    sa.Column('game_word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_word_id'], ['games_words.game_word_id'], name=op.f('fk_games_words_link_authors_game_word_id_games_words')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_games_words_link_authors_user_id_users')),
    sa.PrimaryKeyConstraint('game_word_id', 'user_id', name=op.f('pk_games_words_link_authors'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_words_link_authors')
    # ### end Alembic commands ###
